name: Pull Request Reviewed

on:
  push:
  

jobs:
  save-pr-number:
    name: Save PR Number
    runs-on: ubuntu-latest
    steps:
      - name: down artifact
        run: echo 'echo 1234' > PR_NUMBER.txt
      - uses: actions/upload-artifact@v4
        with:
          name: PR_NUMBER.txt
          path: PR_NUMBER.txt
